apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.app.wlxCustomerName }}-{{ .Values.app.name }}-realtime
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ .Values.app.wlxCustomerName }}-{{ .Values.app.name }}-realtime
  minReplicas: {{ .Values.hpa.minReplicas }}  ## 2
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.averageCPUUtilization }}
