{{- $appName := .Values.app.name -}}
{{- range $fileGroup := .Values.secret.fileGroups }}
  {{- if or (not (hasKey $fileGroup "enabled")) $fileGroup.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $appName }}-{{ $fileGroup.name }}
type: Opaque
data:
    {{- range $file := $fileGroup.fileList }}
      {{- $filePath := printf "%s%s%s" $.Values.secret.filesPath $fileGroup.groupPath $file }}
      {{- . | nindent 2 }}: |
        {{- $.Files.Get $filePath | b64enc | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}