apiVersion: v1
kind: Service
metadata:
  name: test-wlx-realtime
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags:
      Name=test-wlx-realtime,
      Created_By=,
      BudgetTeam=,
      EnvType=,
      Environment=,
      Service=,
      Team=
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: test-wlx-realtime
  ports:
    - protocol: TCP
      port: 2345
      targetPort: 2345
      name: listener-port
    - protocol: TCP
      port: 2346
      targetPort: 2346
      name: gsoap-web-server-port
    - protocol: TCP
      port: 2347
      targetPort: 2347
      name: web-server-port
    - protocol: TCP
      port: 2348
      targetPort: 2348
      name: ais-broker-port
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http-port
