apiVersion: apps/v1
kind: Deployment
metadata:
  name: actone10-deployment
  labels:
    app: actone10-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actone10-deployment
  template:
    metadata:
      labels:
        app: actone10-deployment
    spec:
      containers:
      - name: actone10-container
        image: localhost:5000/actone10:latest
        imagePullPolicy: Always
        env:
          - name: JAVA_OPTS
            value: "-Xms256m -Xmx4096m"
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "4096Mi"
            cpu: "1000m"
        volumeMounts:
        - name: actone10-workdir
          mountPath: /usr/local/tomcat/actone-workdir
      volumes:
      - name: actone10-workdir
        persistentVolumeClaim:
          claimName: actone10-workdir-pvc
          readOnly: false
