apiVersion: v1
kind: PersistentVolume
metadata:
  name: actone10-workdir-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  storageClassName: hostpath
  claimRef:
    namespace: default
    name: actone10-workdir-pvc
  hostPath:
    path: /mnt/data/actone10-workdir
    type: DirectoryOrCreate
