apiVersion: apps/v1
kind: Deployment
metadata:
  name: actone10-deployment
  labels:
    app: actone10-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actone10-deployment
  template:
    metadata:
      labels:
        app: actone10-deployment
    spec:
      containers:
      - name: actone10-container
        image: localhost:5000/actone10:latest
        imagePullPolicy: Always
        #env:
        #    - name: CATALINA_OPTS
        #      value: -Dactimize.ini.location=/data/actone-workdir/config/acm.ini;-Dactimize.jreport.home=/data/actone-workdir/jreport
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        volumeMounts:
        - name: actone10-workdir
          mountPath: /usr/local/tomcat
      volumes:
      - name: actone10-workdir
        persistentVolumeClaim:
          claimName: actone10-workdir-pvc
          readOnly: false
