apiVersion: v1
kind: PersistentVolume
metadata:
  name: actone10-workdir-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  storageClassName: actone10-workdir-pvc
  claimRef:
    namespace: default
    name: actone10-workdir-pvc
  mountOptions:
    - implicit-dirs
  hostPath:
    path: /mnt/data/actone10-workdir
    type: DirectoryOrCreate
