apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: q2-actone10-workdir-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: q2-actone10-workdir-pv
  storageClassName: hostpath